name: Push Trainer to Replicate

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: "Enter the trainer model name, e.g., 'miike-ai/flux-schnell-lora-trainer'"
        required: false  # Optional if you want a default

jobs:
  push_trainer:
    name: Push Trainer to Replicate
    runs-on: ubuntu-latest

    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          docker-images: false

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      - name: Build Trainer Model
        run: cog build

      - name: Push Trainer to Replicate
        run: cog push r8.im/${{ inputs.model_name || 'miike-ai/flux-schnell-lora-trainer' }}

      - name: Clean Up
        run: |
          echo "Cleaning up temporary files"
          rm -rf /tmp/*
